Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/blancheh/SystemsAnalysis/systems-papers/python/semantic_scholar/find_founds_gA.py", line 18, in <module>
    for ten in range(0,4)
  File "/home/blancheh/SystemsAnalysis/systems-papers/python/semantic_scholar/find_founds_gA.py", line 19, in <listcomp>
    for one in range(0,10) ]
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
MemoryError
